name:                posits
version:             0.0.1.0
github:              "GarkGarcia/posits"
license:             GPL-3
author:              "Gark Garcia"
maintainer:          "gark.escobar@protonmail.com"
copyright:           "2020 Gark Garcia"

extra-source-files:
- README.md
- src/lib.c

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/GarkGarcia/posits#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  posits-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - posits

