flags:
  transformers-compat:
    five: true
packages:
- .
extra-deps:
- binary-0.8.7.0
- blaze-builder-0.4.1.0
- hashable-1.3.0.0
- microlens-0.4.11.2
- microlens-mtl-0.2.0.1
- microlens-th-0.4.3.2
- mtl-2.2.2
- parallel-3.2.2.0
- parsec-3.1.14.0
- parsec-numbers-0.1.0
- primitive-0.6.4.0
- split-0.2.3.3
- stm-2.5.0.0
- text-1.2.4.0
- th-abstraction-0.3.1.0
- transformers-compat-0.6.4
- utf8-string-1.0.1.1
- vector-0.12.0.3
- vty-5.26
- haskeline-0.8.0.0
- exceptions-0.10.4
resolver: ghc-8.0.2
